name: CI — Docker Build Test

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker:
    name: Build & Docker
    runs-on: ubuntu-latest

    steps:

      - name: Checkout app
        uses: actions/checkout@v6

      - name: Checkout composite action
        uses: actions/checkout@v6
        with:
          repository: tusharkumarshahi/test-mule-actions
          path: .github/actions/docker-build

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Maven build
        run: mvn clean package -B -DskipTests=true

      - name: Docker Build and Push
        id: docker
        uses: ./.github/actions/docker-build
        with:
          image-name: test-maven-app
          image-tag: ${{ github.sha }}
          push: 'false'

      - name: Print image ref
        run: echo "Built ${{ steps.docker.outputs.image-full-ref }}"
