name: CI — Maven Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout app code
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: tusharkumarshahi/test-mule-actions/.github/actions/maven-build@main

      - name: Show artifact
        run: |
          echo "Built artifact: ${{ steps.build.outputs.artifact-path }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: ${{ steps.build.outputs.artifact-path }}
          retention-days: 1
